[2024-07-22T22:36:31.002-0300] {processor.py:161} INFO - Started process (PID=1050592) to work on /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:36:31.002-0300] {processor.py:830} INFO - Processing file /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-22T22:36:31.003-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:36:31.003-0300] {dagbag.py:545} INFO - Filling up the DagBag from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:36:31.006-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:36:31.005-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-22T22:36:31.006-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:36:31.006-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-22T22:36:31.006-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:36:31.014-0300] {processor.py:183} INFO - Processing /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-07-22T22:37:22.864-0300] {processor.py:161} INFO - Started process (PID=1051150) to work on /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:37:22.865-0300] {processor.py:830} INFO - Processing file /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-22T22:37:22.867-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:37:22.866-0300] {dagbag.py:545} INFO - Filling up the DagBag from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:37:22.869-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:37:22.868-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-22T22:37:22.869-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:37:22.869-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-22T22:37:22.869-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:37:22.876-0300] {processor.py:183} INFO - Processing /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-07-22T22:38:11.787-0300] {processor.py:161} INFO - Started process (PID=1051676) to work on /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:11.792-0300] {processor.py:830} INFO - Processing file /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-22T22:38:11.794-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:11.793-0300] {dagbag.py:545} INFO - Filling up the DagBag from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:11.796-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:11.795-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-22T22:38:11.796-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:11.796-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-22T22:38:11.796-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:11.804-0300] {processor.py:183} INFO - Processing /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-07-22T22:38:56.512-0300] {processor.py:161} INFO - Started process (PID=1052196) to work on /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:56.513-0300] {processor.py:830} INFO - Processing file /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-22T22:38:56.515-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:56.514-0300] {dagbag.py:545} INFO - Filling up the DagBag from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:56.518-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:56.517-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-22T22:38:56.518-0300] {logging_mixin.py:188} INFO - [2024-07-22T22:38:56.518-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-22T22:38:56.518-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-22T22:38:56.526-0300] {processor.py:183} INFO - Processing /home/hugoviana/Projetos/crypto-etl/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
