[2024-07-25T14:27:15.940-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:15.945-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:27:15.948-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:27:15.948-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:15.961-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:00:00+00:00
[2024-07-25T14:27:15.963-0300] {standard_task_runner.py:64} INFO - Started process 2590020 to run task
[2024-07-25T14:27:15.965-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:00:00+00:00', '--job-id', '2082', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmppo3xklxf']
[2024-07-25T14:27:15.966-0300] {standard_task_runner.py:91} INFO - Job 2082: Subtask get_5m_info
[2024-07-25T14:27:15.990-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:16.037-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:00:00+00:00'
[2024-07-25T14:27:16.037-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:16.044-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:16.044-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:16.050-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:00:00+00:00, execution_date=20240725T120000, start_date=20240725T172715, end_date=20240725T172716
[2024-07-25T14:27:16.060-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2082 for task get_5m_info (too many values to unpack (expected 2); 2590020)
[2024-07-25T14:27:16.099-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:16.105-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:16.105-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:29:56.786-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:29:56.792-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:29:56.795-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:29:56.795-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:29:56.808-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:00:00+00:00
[2024-07-25T14:29:56.810-0300] {standard_task_runner.py:64} INFO - Started process 2592800 to run task
[2024-07-25T14:29:56.811-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:00:00+00:00', '--job-id', '2082', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpqhtk37fn']
[2024-07-25T14:29:56.812-0300] {standard_task_runner.py:91} INFO - Job 2082: Subtask get_5m_info
[2024-07-25T14:29:56.839-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:29:56.884-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:00:00+00:00'
[2024-07-25T14:29:56.884-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:29:56.891-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:29:56.891-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:29:56.894-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:00:00+00:00, execution_date=20240725T120000, start_date=20240725T172956, end_date=20240725T172956
[2024-07-25T14:29:56.905-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2082 for task get_5m_info (too many values to unpack (expected 2); 2592800)
[2024-07-25T14:29:56.945-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:29:56.951-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:29:56.951-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:49:16.808-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:49:16.815-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:49:16.819-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:49:16.819-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:49:16.833-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:00:00+00:00
[2024-07-25T14:49:16.835-0300] {standard_task_runner.py:64} INFO - Started process 2608645 to run task
[2024-07-25T14:49:16.837-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:00:00+00:00', '--job-id', '2154', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp5_vawr9b']
[2024-07-25T14:49:16.838-0300] {standard_task_runner.py:91} INFO - Job 2154: Subtask get_5m_info
[2024-07-25T14:49:16.867-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:49:16.911-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:00:00+00:00'
[2024-07-25T14:49:16.912-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:49:16.924-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T14:49:16.925-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721919900&from=1721919600
[2024-07-25T14:49:17.303-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T14:49:17.304-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:49:17.307-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:00:00+00:00, execution_date=20240725T120000, start_date=20240725T174916, end_date=20240725T174917
[2024-07-25T14:49:17.338-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T14:49:17.344-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:49:17.344-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:59:51.779-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:59:51.784-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:59:51.789-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T14:59:51.789-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:59:51.806-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:00:00+00:00
[2024-07-25T14:59:51.807-0300] {standard_task_runner.py:64} INFO - Started process 2619313 to run task
[2024-07-25T14:59:51.810-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:00:00+00:00', '--job-id', '2455', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp14qphtdj']
[2024-07-25T14:59:51.811-0300] {standard_task_runner.py:91} INFO - Job 2455: Subtask get_5m_info
[2024-07-25T14:59:51.845-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:59:51.904-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:00:00+00:00'
[2024-07-25T14:59:51.904-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:59:51.983-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T14:59:51.984-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721919900&from=1721919600
[2024-07-25T14:59:52.270-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T14:59:52.271-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:59:52.273-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:00:00+00:00, execution_date=20240725T120000, start_date=20240725T175951, end_date=20240725T175952
[2024-07-25T14:59:52.309-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T14:59:52.317-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:59:52.317-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T17:20:22.607-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T17:20:22.613-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T17:20:22.617-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [queued]>
[2024-07-25T17:20:22.617-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T17:20:22.632-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:00:00+00:00
[2024-07-25T17:20:22.634-0300] {standard_task_runner.py:64} INFO - Started process 2691745 to run task
[2024-07-25T17:20:22.636-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:00:00+00:00', '--job-id', '2475', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp983nr0gi']
[2024-07-25T17:20:22.637-0300] {standard_task_runner.py:91} INFO - Job 2475: Subtask get_5m_info
[2024-07-25T17:20:22.679-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:00:00+00:00 [running]> on host Galaxybook.
[2024-07-25T17:20:22.726-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:00:00+00:00'
[2024-07-25T17:20:22.727-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T17:20:22.734-0300] {mercado_dag.py:21} INFO - To: 2024-07-25 12:01:00+00:00
[2024-07-25T17:20:22.734-0300] {mercado_dag.py:22} INFO - From: 2024-07-25 12:00:00+00:00
[2024-07-25T17:20:22.735-0300] {mercado_dag.py:23} INFO - To timestamp: 1721908860 
[2024-07-25T17:20:22.735-0300] {mercado_dag.py:24} INFO - From timestamp: 1721908800 
[2024-07-25T17:20:22.739-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T17:20:22.740-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=1m&to=1721908860&from=1721908800
[2024-07-25T17:20:23.024-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T17:20:23.088-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T17:20:23.090-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:00:00+00:00, execution_date=20240725T120000, start_date=20240725T202022, end_date=20240725T202023
[2024-07-25T17:20:23.139-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T17:20:23.147-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T17:20:23.147-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
